//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetkProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> IdStudent { get; set; }
        public Nullable<int> IdTeacher { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
